#!A:\Ale_GitHub\2025_GenAIEngineering\06_PythonBaseCamp\GenAIEngineering-Cohort2\week9_venv\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
